### ISSUE TITLE
Support for monorepos

### ISSUE THREAD

**Issue by vio** [relative-ci/roadmap#30]

**Comment by promontis** [comment]
+1

**Comment by gjsduarte** [comment]
Any news on how can we use `relative-ci` in a monorepo?

**Comment by vio** [comment]
Hi @gjsduarte! Sorry, I forgot to update the issue, this is currently in progress and will be available for beta testing soon.

**Comment by gjsduarte** [comment]
Looking forward to test that 😊

**Comment by vio** [comment]
# 🚀  Monorepo support is now in public beta

Once you have an existing organization/project:
1. Follow the setup steps
2. Check CI configuration differences

Let me know if you encounter any issues or if you need assistance setting up the CI.

----

## Setup steps:

### Step 1. Navigate to the organization page and click 'Add project'

![1-organization-view](https://user-images.githubusercontent.com/13300/140973227-06b83c2a-e3c9-485d-8947-6429b8ccb930.png)

### Step 2. Click on "Check available GitHub installations"

![2-add-project](https://user-images.githubusercontent.com/13300/140973486-64662cc8-f1f2-4ffe-97b3-49a136c32249.png)

### Step 3. Select the repository

The list will show all the repositories with RelativeCI GitHub app installations no matter if they correspond to a RelativeCI project. 

![3-select-repo](https://user-images.githubusercontent.com/13300/140973726-b25786c3-643b-4f1d-a5f1-8681a6cd8555.png)

### Step 4. Enter project details

![4-project-details](https://user-images.githubusercontent.com/13300/140973807-4401553d-eefc-4f97-a1e1-5b691a6eb56e.png)

## CI configuration

The CI configuration is the same as for a single project, except that you need to add and pass secrets for each project in case you run the build process for multiple projects on the same CI workflow:

```
PROJECT_1_RELATIVE_CI_KEY=*** 
PROJECT_2_RELATIVE_CI_KEY=*** 
```

Depending on your configuration method, you will need to pass corresponding keys to each task:

```yaml
// .github/workflows/build.yaml
....
      - name: Build project 1
        run: npm run build --if-present
        env:
          RELATIVE_CI_KEY: ${{ secrets.PROJECT_1_RELATIVE_CI_KEY }}
...
      - name: Build project 2
        run: npm run build --if-present
        env:
          RELATIVE_CI_KEY: ${{ secrets.PROJECT_2_RELATIVE_CI_KEY }}

```

Example repository: https://github.com/relative-ci/example-webpack-plugin-github-action-monorepo
